keys:
  - &user 06CEA7F23ADCA705
  - &desktop age1z5vvm6gk09jfqxcwpdw6l8hxjteqn8z4vwd6es0qsuuf6slj732qcu9fsh

creation_rules:
  - path_regex: '[^/]+\.(yaml|json|env|ini)$'
    key_groups:
      - pgp:
          - *user
        age:
          - *desktop
